In [4]:
import numpy as np
a= np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
print(a)

transpose=a.T
print(transpose)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [5]:
matrix = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

# Print the original matrix
print("Original matrix:")
for row in matrix:
    print(row)

# Find the transpose
transpose = []
for i in range(len(matrix[0])):  # Iterate through columns
    transposed_row = []
    for row in matrix:           # Iterate through rows
        transposed_row.append(row[i])
    transpose.append(transposed_row)

# Print the transposed matrix
print("\nTransposed matrix:")
for row in transpose:
    print(row)

Original matrix:
[1, 2, 3]
[4, 5, 6]
[7, 8, 9]

Transposed matrix:
[1, 4, 7]
[2, 5, 8]
[3, 6, 9]
